ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_PROVIDER_ID
ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_PATIENT_ID
ALTER TABLE DRUG_TREATMENT DROP CONSTRAINT FK_DRUG_TREATMENT_ID
ALTER TABLE SURGERY DROP CONSTRAINT FK_SURGERY_ID
ALTER TABLE RADIOLOGY DROP CONSTRAINT FK_RADIOLOGY_ID
ALTER TABLE Radiology_dates DROP CONSTRAINT FK_Radiology_dates_RadiologyTreatment_ID
DROP TABLE Patient CASCADE
DROP TABLE Treatment CASCADE
DROP TABLE DRUG_TREATMENT CASCADE
DROP TABLE Provider CASCADE
DROP TABLE SURGERY CASCADE
DROP TABLE RADIOLOGY CASCADE
DROP TABLE Radiology_dates CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
