ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_PATIENT_ID
ALTER TABLE TREATMENT DROP CONSTRAINT FK_TREATMENT_PROVIDER_ID
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT FK_DRUGTREATMENT_ID
ALTER TABLE SURGERY DROP CONSTRAINT FK_SURGERY_ID
ALTER TABLE RADIOLOGY DROP CONSTRAINT FK_RADIOLOGY_ID
ALTER TABLE Radiology_dates DROP CONSTRAINT FK_Radiology_dates_RadiologyTreatment_ID
DROP TABLE PATIENT CASCADE
DROP TABLE PROVIDER CASCADE
DROP TABLE TREATMENT CASCADE
DROP TABLE DRUGTREATMENT CASCADE
DROP TABLE SURGERY CASCADE
DROP TABLE RADIOLOGY CASCADE
DROP TABLE Radiology_dates CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
